language: python
python:
  - "3.6"

before_install:
  - pip install --user codecov

install:
   - pip install coveralls

script: 
  - coverage run -m unittest
  - coverage report
  
after_success:
  - codecov --file coverage/lcov.info --disable search